# Configuration file for AI Security Assistant

groq_api_key: "YOUR_GROQ_API_KEY_HERE"

telegram:
  token: "YOUR_TELEGRAM_BOT_TOKEN"
  chat_id: "YOUR_TELEGRAM_CHAT_ID"

discord:
  webhook_url: "YOUR_DISCORD_WEBHOOK_URL"

scan:
  targets:
    - "http://example.com"
    - "http://testsite.local"
  interval_seconds: 3600

logging:
  level: "INFO"
